# Generated by Django 6.0.7 on 2026-07-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='seat_prefix',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='total_seats',
            field=models.IntegerField(default=0),
        ),
    ]
