# Generated by Django 6.0.7 on 2026-07-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_subscriptionplan_seat_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('UPGRADED', 'Upgraded'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
    ]
