# Generated by Django 6.0.7 on 2026-07-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('UPCOMING', 'Upcoming'), ('UPGRADED', 'Upgraded'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
    ]
