# Generated by Django 6.0.7 on 2026-07-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_amount_paid_booking_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
