# Generated by Django 6.0.7 on 2026-07-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_contactmessage_is_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_1_year',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_3_months',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_6_months',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
