# Generated by Django 6.0.7 on 2026-09-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_transaction_id_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='access_hours',
            field=models.CharField(default='9 AM - 9 PM', max_length=255),
        ),
    ]
