[pytest]
DJANGO_SETTINGS_MODULE = core.settings_test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --strict-markers
norecursedirs = .git .pytest_cache __pycache__ venv
testpaths = accounts bookings core
markers =
    slow: marks tests as slow
